### ISSUE TITLE
Is there any defense against ingesting the same record twice which de-syncs the degree table.

### ISSUE THREAD

**Issue by medined** [medined/D4M_Schema#1]
Might be worth writing a 'synchronization check' tool which can be run once in  a while.

**Comment by dhutchis** [comment]
No, as long as the tables are separate.  No one can stop an "evil Eve" client with access to your database from ingesting bad records, including re-ingesting legitimate records to the degree table.  However, you're usually in a situation where you can trust users with write access to the database.

On the client-side, one could check for duplicate additions by doing a scan on the regular or transpose table prior to ingest, but the performance penalty of the client is seldom worth it.  Just ingest your data once.  Trust Accumulo's fault tolerance to handle cases of failure.

If you're thinking about a distributed sampling algorithm where the same data may be ingested at multiple locations and coordination is not feasible, consider allowing sampling the same data point twice.  Seems like a rare occurrence in most big data scenarios.

**Comment by medined** [comment]
Thanks.

**Comment by dhutchis** [comment]
Forgot to mention, you can check the validity of a degree count in the degree table by scanning the degree table.  Using the example on the front page, to find the degree of STATE_NAME|MAINE, just scan the transpose table for all the columns in the row STATE_NAME|MAINE and count how many results are returned.  This defeats the purpose of the degree table in improving query performance, but if checking table sanity periodically is critical you can do it.

In D4M Matlab syntax, the following are equivalent:

``` Matlab
Tmd('weight|195,',:)
nnz(Tm(:,StartsWith('weight|195,')))
```

where `Tmd` is the edge table and `Tm` is the regular-transpose table pair.  Of course, the first line saves a bunch of scanning.

Likewise this also applies to the TedgeField entries.  The following are equivalent:

``` Matlab
Tef('weight,',:)
sum( str2num(Tmd(StartsWith('weight|,'),:)), 1)
```

where `Tef` is the edge field table.
